export const objects = [
  "Golf cart",
  "Falcon",
  "Mammal",
  "Tin can",
  "Snack",
  "Harpsichord",
  "Rhinoceros",
  "Milk",
  "Wine glass",
  "Necklace",
  "Human hair",
  "Lily",
  "Bathroom accessory",
  "Dress",
  "Mixing bowl",
  "Flute",
  "Bird",
  "Pomegranate",
  "Cabbage",
  "Pencil case",
  "Saxophone",
  "Stapler",
  "Dice",
  "Frog",
  "Waffle",
  "Porcupine",
  "Tie",
  "Horn",
  "Printer",
  "Pear",
  "Beer",
  "Accordion",
  "Tennis racket",
  "Tomato",
  "Desk",
  "Violin",
  "Common fig",
  "Lantern",
  "High heels",
  "Sunglasses",
  "Spice rack",
  "Vehicle registration plate",
  "Heater",
  "Adhesive tape",
  "Measuring cup",
  "Swimming pool",
  "Human leg",
  "Musical instrument",
  "Spatula",
  "Volleyball",
  "Teapot",
  "Boy",
  "Fox",
  "Training bench",
  "Baseball glove",
  "Light switch",
  "Cricket ball",
  "Whisk",
  "Rocket",
  "Grapefruit",
  "Mushroom",
  "Wine rack",
  "Scale",
  "Pen",
  "Turtle",
  "Cupboard",
  "Camera",
  "Light bulb",
  "Sewing machine",
  "Piano",
  "Human nose",
  "Dumbbell",
  "Pizza",
  "Digital clock",
  "Glasses",
  "Beehive",
  "Tableware",
  "Coconut",
  "Hot dog",
  "Ostrich",
  "Towel",
  "Fruit",
  "Baseball bat",
  "Popcorn",
  "Oboe",
  "Lobster",
  "Sheep",
  "Personal care",
  "Fast food",
  "Bicycle",
  "Guitar",
  "Ruler",
  "Tent",
  "Traffic light",
  "Cream",
  "Zucchini",
  "Spoon",
  "Jug",
  "Studio couch",
  "Plumbing fixture",
  "Dolphin",
  "Coin",
  "Sandal",
  "Skyscraper",
  "Cocktail shaker",
  "Ant",
  "Ladybug",
  "Raven",
  "Diaper",
  "Alarm clock",
  "Stool",
  "Dishwasher",
  "Billboard",
  "Human head",
  "Candy",
  "Ratchet",
  "Banjo",
  "Girl",
  "Table",
  "Sink",
  "Tire",
  "Tap",
  "Hippopotamus",
  "Cattle",
  "Tablet computer",
  "Airplane",
  "Racket",
  "Wheelchair",
  "Stretcher",
  "Football helmet",
  "Dessert",
  "Footwear",
  "Curtain",
  "Cart",
  "Bat",
  "Ball",
  "Train",
  "Blender",
  "Sports uniform",
  "Maple",
  "Man",
  "Shrimp",
  "Hedgehog",
  "Ceiling fan",
  "Poster",
  "Sunflower",
  "Computer mouse",
  "Drill",
  "Marine mammal",
  "Kitchen utensil",
  "Lynx",
  "Tennis ball",
  "Tea",
  "Scarf",
  "Shark",
  "Toilet paper",
  "Doughnut",
  "Toothbrush",
  "Aircraft",
  "Panda",
  "Syringe",
  "Gondola",
  "Snowboard",
  "Croissant",
  "Serving tray",
  "Saucer",
  "House",
  "Human foot",
  "Fire hydrant",
  "Orange",
  "Carnivore",
  "Plant",
  "Golf ball",
  "Door handle",
  "Paper towel",
  "Muffin",
  "Furniture",
  "Cookie",
  "Vehicle",
  "Isopod",
  "Stairs",
  "Motorcycle",
  "Chainsaw",
  "Candle",
  "Otter",
  "Artichoke",
  "Porch",
  "Helmet",
  "Earrings",
  "Dairy",
  "Microphone",
  "Eagle",
  "Infant bed",
  "Fountain",
  "Kite",
  "Table tennis racket",
  "Traffic sign",
  "Door",
  "Sofa bed",
  "Shorts",
  "Winter melon",
  "Toilet",
  "Flower",
  "Tree house",
  "Deer",
  "Submarine sandwich",
  "Treadmill",
  "Bronze sculpture",
  "Giraffe",
  "Cake",
  "Bicycle helmet",
  "Dog",
  "Building",
  "Clothing",
  "Skunk",
  "Scorpion",
  "Boot",
  "Shirt",
  "Wheel",
  "Vegetable",
  "Barge",
  "Window blind",
  "Christmas tree",
  "Goat",
  "Axe",
  "Glove",
  "Sea lion",
  "Headphones",
  "Closet",
  "Sun hat",
  "Chisel",
  "Cheese",
  "Segway",
  "Swim cap",
  "Ambulance",
  "Butterfly",
  "Goldfish",
  "Fax",
  "Lighthouse",
  "Auto part",
  "Radish",
  "Cheetah",
  "Coffee table",
  "Scoreboard",
  "Kangaroo",
  "Human arm",
  "Knife",
  "Human eye",
  "Kitchen appliance",
  "Screwdriver",
  "Shelf",
  "Carrot",
  "Telephone",
  "Window",
  "Balance beam",
  "Suit",
  "Punching bag",
  "French fries",
  "Koala",
  "Mixer",
  "Pretzel",
  "Skateboard",
  "Countertop",
  "Rose",
  "Alpaca",
  "Elephant",
  "Sock",
  "Power plugs and sockets",
  "Shotgun",
  "Belt",
  "Flowerpot",
  "Suitcase",
  "Umbrella",
  "Squash",
  "Watch",
  "Weapon",
  "Unicycle",
  "Bottle",
  "Cocktail",
  "Computer monitor",
  "Clock",
  "Chicken",
  "Egg",
  "Tiara",
  "Cake stand",
  "Willow",
  "Nightstand",
  "Fashion accessory",
  "Horizontal bar",
  "Sculpture",
  "Handbag",
  "Box",
  "Eraser",
  "Juice",
  "Jeans",
  "Hammer",
  "Dinosaur",
  "Goggles",
  "Seat belt",
  "Shellfish",
  "Hand dryer",
  "Tank",
  "Briefcase",
  "Hiking equipment",
  "Magpie",
  "Wall clock",
  "Filing cabinet",
  "Musical keyboard",
  "Face powder",
  "Asparagus",
  "Pineapple",
  "Sparrow",
  "Peach",
  "Scissors",
  "Canoe",
  "Corded phone",
  "Starfish",
  "Bathtub",
  "Waffle iron",
  "Bicycle wheel",
  "Wardrobe",
  "Chair",
  "Dog bed",
  "Sea turtle",
  "Invertebrate",
  "Roller skates",
  "Parachute",
  "Wood-burning stove",
  "Ice cream",
  "Swimwear",
  "Polar bear",
  "Oven",
  "Cutting board",
  "Coffeemaker",
  "Miniskirt",
  "Street light",
  "Paddle",
  "Ladder",
  "Skirt",
  "Mule",
  "Goose",
  "Human face",
  "Slow cooker",
  "Gas stove",
  "Jacket",
  "Houseplant",
  "Pitcher",
  "Bagel",
  "Monkey",
  "Tortoise",
  "Lifejacket",
  "Rays and skates",
  "Raccoon",
  "Cat",
  "Helicopter",
  "Tripod",
  "Surfboard",
  "Spider",
  "Waste container",
  "Food processor",
  "Watermelon",
  "Cantaloupe",
  "Sombrero",
  "Mango",
  "Honeycomb",
  "Human hand",
  "Stethoscope",
  "Parking meter",
  "Wrench",
  "Shower",
  "Sushi",
  "Cabinetry",
  "Sword",
  "Banana",
  "Lipstick",
  "Book",
  "Salt and pepper shakers",
  "Seahorse",
  "Hat",
  "Medical equipment",
  "Television",
  "Billiard table",
  "Brown bear",
  "Reptile",
  "Cosmetics",
  "Bowling equipment",
  "Watercraft",
  "Crab",
  "Coffee",
  "Chest of drawers",
  "Broccoli",
  "Office supplies",
  "Trombone",
  "Humidifier",
  "Marine invertebrates",
  "Dragonfly",
  "Drum",
  "Home appliance",
  "Squirrel",
  "Toaster",
  "Strawberry",
  "Harbor seal",
  "Pastry",
  "Hamburger",
  "Seafood",
  "Jet ski",
  "Coat",
  "Bidet",
  "Loveseat",
  "Land vehicle",
  "Wine",
  "Human body",
  "Skull",
  "Duck",
  "Cello",
  "Convenience store",
  "Moths and butterflies",
  "Human beard",
  "Toy",
  "Snowmobile",
  "Swan",
  "Mouse",
  "Horse",
  "Backpack",
  "Computer keyboard",
  "Trumpet",
  "Tiger",
  "Fork",
  "Apple",
  "Bear",
  "Football",
  "Bus",
  "Human mouth",
  "Blue jay",
  "Picture frame",
  "Flashlight",
  "Bread",
  "Whiteboard",
  "Pig",
  "Hamster",
  "Beaker",
  "Kitchen & dining room table",
  "Woman",
  "Hair dryer",
  "Platter",
  "Luggage and bags",
  "Grape",
  "Crocodile",
  "Kitchen knife",
  "Lizard",
  "Food",
  "Bottle opener",
  "Picnic basket",
  "Doll",
  "Van",
  "Envelope",
  "Binoculars",
  "Pumpkin",
  "Drinking straw",
  "Caterpillar",
  "Chopsticks",
  "Canary",
  "Remote control",
  "Tree",
  "Submarine",
  "Worm",
  "Handgun",
  "Calculator",
  "Mechanical fan",
  "Tart",
  "Drawer",
  "Perfume",
  "Potato",
  "Crown",
  "Fireplace",
  "Mobile phone",
  "Car",
  "Limousine",
  "Pillow",
  "Snail",
  "Missile",
  "Zebra",
  "Fish",
  "Rifle",
  "Pasta",
  "Dagger",
  "Trousers",
  "Sports equipment",
  "Leopard",
  "Human ear",
  "Antelope",
  "Parrot",
  "Mirror",
  "Bust",
  "Cannon",
  "Vase",
  "Guacamole",
  "Salad",
  "Cowboy hat",
  "Woodpecker",
  "Squid",
  "Camel",
  "Microwave oven",
  "Turkey",
  "Ring binder",
  "Lavender",
  "Pancake",
  "Refrigerator",
  "Penguin",
  "Balloon",
  "Baked goods",
  "Insect",
  "Bull",
  "Frying pan",
  "Laptop",
  "Sandwich",
  "Fedora",
  "Burrito",
  "Jaguar",
  "Person",
  "Bed",
  "Cucumber",
  "Flying disc",
  "Barrel",
  "Beetle",
  "Centipede",
  "Stop sign",
  "Bathroom cabinet",
  "Can opener",
  "Couch",
  "Castle",
  "Plastic bag",
  "Jellyfish",
  "Lemon",
  "Oyster",
  "Stationary bicycle",
  "Ski",
  "Soap dispenser",
  "Palm tree",
  "Lamp",
  "Snowman",
  "Taxi",
  "Bench",
  "Organ",
  "Mug",
  "Coffee cup",
  "Harp",
  "Bowl",
  "Washing machine",
  "Owl",
  "Bookcase",
  "Tick",
  "Animal",
  "Red panda",
  "Armadillo",
  "Bell pepper",
  "Cassette deck",
  "Nail",
  "Lion",
  "Drink",
  "Wok",
  "Bee",
  "Whale",
  "Taco",
  "Boat",
  "Cat furniture",
  "Flag",
  "Truck",
  "Teddy bear",
  "Tool",
  "Rugby ball",
  "Brassiere",
  "Rabbit",
  "Jacuzzi",
  "Snake",
  "Ipod",
  "Office building",
  "Bow and arrow",
  "Kettle",
  "Plate",
  "Snowplow",
  "Tower",
];
